# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
clone:
  depth: full
  
pipelines:
  default:
    - step:
        script:
          - git push --mirror git@github.com:kcha193/anova_test.git
